-- Creator storefront customization
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_tagline TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_bg_color TEXT NOT NULL DEFAULT '#0a0a0b';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_bg_image TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_text_color TEXT NOT NULL DEFAULT '#e4e4e7';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_accent_color TEXT NOT NULL DEFAULT '#6366f1';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_card_bg TEXT NOT NULL DEFAULT '#18181b';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_card_border TEXT NOT NULL DEFAULT '#27272a';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_font TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_font_size TEXT NOT NULL DEFAULT '14px';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_cursor TEXT NOT NULL DEFAULT 'default';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_layout TEXT NOT NULL DEFAULT 'grid';
ALTER TABLE users ADD COLUMN IF NOT EXISTS storefront_css TEXT NOT NULL DEFAULT '';
